import type { INodeProperties } from 'n8n-workflow';
import { CANDIDATE_MODES, USER_MODES } from './SharedFields';

export const candidateOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: { resource: ['candidate'] },
		},
		options: [
			{
				name: 'Create',
				value: 'create',
				action: 'Create a candidate',
				description: 'Create a new candidate',
			},
			{
				name: 'Get',
				value: 'get',
				action: 'Get a candidate',
				description: 'Retrieve a candidate by ID',
			},
			{
				name: 'Get Many',
				value: 'getMany',
				action: 'Get many candidates',
				description: 'Retrieve a list of candidates',
			},
			{
				name: 'Update',
				value: 'update',
				action: 'Update a candidate',
				description: "Update partially a candidate's details",
			},
		],
		default: 'getMany',
	},
];

const GENDER_OPTIONS = [
	{ name: 'Female', value: 'female' },
	{ name: 'Male', value: 'male' },
	{ name: 'Other', value: 'other' },
	{ name: 'Unknown', value: 'unknown' },
];

const SOURCE_TYPE_OPTIONS = [
	{ name: 'Agency', value: 'agency' },
	{ name: 'Applied', value: 'applied' },
	{ name: 'Other', value: 'other' },
	{ name: 'Referred', value: 'referred' },
	{ name: 'Sourced', value: 'sourced' },
];

export const candidateFields: INodeProperties[] = [
	{
		displayName: 'Candidate ID',
		name: 'candidateId',
		type: 'resourceLocator',
		required: true,
		default: { mode: 'list', value: '' },
		modes: CANDIDATE_MODES,
		displayOptions: {
			show: { resource: ['candidate'], operation: ['get'] },
		},
		description: 'Numeric ID of the candidate to retrieve',
	},

	// GET MANY
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		default: false,
		displayOptions: {
			show: { resource: ['candidate'], operation: ['getMany'] },
		},
		description: 'Fetch every matching candidate instead of stopping at the limit',
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		typeOptions: { minValue: 1, maxValue: 100 },
		default: 10,
		displayOptions: {
			show: { resource: ['candidate'], operation: ['getMany'], returnAll: [false] },
		},
		description: 'Max number of results to return',
	},
	{
		displayName: 'Filters',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add Filter',
		default: {},
		displayOptions: {
			show: { resource: ['candidate'], operation: ['getMany'] },
		},
		options: [
			{
				displayName: 'Address',
				name: 'address',
				type: 'string',
				default: '',
				placeholder: '123 Main Street',
				description: 'Return candidates whose address contains this text (partial match)',
			},
			{
				displayName: 'Birth Date (From)',
				name: 'birth_date__gte',
				type: 'dateTime',
				default: '',
				description: 'Return candidates born on or after this date',
			},
			{
				displayName: 'Birth Date (To)',
				name: 'birth_date__lte',
				type: 'dateTime',
				default: '',
				description: 'Return candidates born on or before this date',
			},
			{
				displayName: 'Candidate Location',
				name: 'candidate_location',
				type: 'string',
				default: '',
				placeholder: 'New York',
				description: 'Return candidates whose location contains this text (partial match)',
			},
			{
				displayName: 'Candidate Tags',
				name: 'candidate_tags',
				type: 'string',
				default: '',
				placeholder: '12123 ,34332,561568',
				description: 'Return candidates that have all of the specified tag IDs (comma-separated)',
			},
			{
				displayName: 'Created At (From)',
				name: 'created_at__gte',
				type: 'dateTime',
				default: '',
				description: 'Return candidates created on or after this date',
			},
			{
				displayName: 'Created At (To)',
				name: 'created_at__lte',
				type: 'dateTime',
				default: '',
				description: 'Return candidates created on or before this date',
			},
			{
				displayName: 'Current Company',
				name: 'current_company',
				type: 'string',
				default: '',
				placeholder: 'Acme Corp',
				description: 'Return candidates whose current company contains this text (partial match)',
			},
			{
				displayName: 'Current Position',
				name: 'current_position',
				type: 'string',
				default: '',
				placeholder: 'Software Engineer',
				description: 'Return candidates whose current position contains this text (partial match)',
			},
			{
				displayName: 'Description',
				name: 'description',
				type: 'string',
				default: '',
				description: 'Return candidates whose description contains this text (partial match)',
			},
			{
				displayName: 'Email',
				name: 'email',
				type: 'string',
				default: '',
				placeholder: 'jane.smith@company.com',
				description: 'Return candidates with this exact email address',
			},
			{
				displayName: 'External ID',
				name: 'external_id',
				type: 'string',
				default: '',
				placeholder: 'EXT-00142',
				description: 'Return candidates with this exact external system ID',
			},
			{
				displayName: 'Full Name',
				name: 'full_name',
				type: 'string',
				default: '',
				placeholder: 'Jane Smith',
				description: 'Return candidates whose name contains this text (partial match)',
			},
			{
				displayName: 'Gender',
				name: 'gender',
				type: 'options',
				default: 'unknown',
				options: GENDER_OPTIONS,
				description: 'Return candidates with this gender value',
			},
			{
				displayName: 'ID',
				name: 'id',
				type: 'number',
				default: '',
				description: 'Return the candidate with this exact ID',
			},
			{
				displayName: 'Latest Degree',
				name: 'latest_degree',
				type: 'string',
				default: '',
				placeholder: 'Bachelor of Science',
				description: 'Return candidates whose latest degree contains this text (partial match)',
			},
			{
				displayName: 'Latest University',
				name: 'latest_university',
				type: 'string',
				default: '',
				placeholder: 'Stanford University',
				description: 'Return candidates whose latest university contains this text (partial match)',
			},
			{
				displayName: 'Owner',
				name: 'owner_id',
				type: 'resourceLocator',
				default: { mode: 'list', value: '' },
				description: 'Return candidates owned by this user',
				modes: USER_MODES,
			},
			{
				displayName: 'Phone Number',
				name: 'phone_number',
				type: 'string',
				default: '',
				placeholder: '+1 555 000 0001',
				description: 'Return candidates with this exact phone number',
			},
			{
				displayName: 'Source Type',
				name: 'source_type',
				type: 'options',
				default: 'sourced',
				options: SOURCE_TYPE_OPTIONS,
				description: 'Return candidates with this source type',
			},
			{
				displayName: 'Updated At (From)',
				name: 'updated_at__gte',
				type: 'dateTime',
				default: '',
				description: 'Return candidates updated on or after this date',
			},
			{
				displayName: 'Updated At (To)',
				name: 'updated_at__lte',
				type: 'dateTime',
				default: '',
				description: 'Return candidates updated on or before this date',
			},
		],
	},

	// CREATE
	{
		displayName: 'Full Name',
		name: 'fullName',
		type: 'string',
		required: true,
		default: '',
		placeholder: 'Jane Smith',
		displayOptions: {
			show: { resource: ['candidate'], operation: ['create'] },
		},
		description: 'Full name of the candidate',
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: { resource: ['candidate'], operation: ['create'] },
		},
		options: [
			{
				displayName: 'Address',
				name: 'address',
				type: 'string',
				default: '',
				placeholder: '123 Main Street',
				description: 'Street address of the candidate',
			},
			{
				displayName: 'Birth Date',
				name: 'birth_date',
				type: 'dateTime',
				default: '',
				description: "Candidate's date of birth",
			},
			{
				displayName: 'Consent',
				name: 'consent',
				type: 'boolean',
				default: false,
				description:
					'Enable to record that the candidate consented to data processing under privacy regulations (GDPR, LGPD, CCPA)',
			},
			{
				displayName: 'Current Company',
				name: 'current_company',
				type: 'string',
				default: '',
				placeholder: 'Acme Corp',
				description: "Name of the candidate's current employer",
			},
			{
				displayName: 'Current Department',
				name: 'current_department',
				type: 'string',
				default: '',
				placeholder: 'Engineering',
				description: 'Department the candidate currently works in',
			},
			{
				displayName: 'Current Position',
				name: 'current_position',
				type: 'string',
				default: '',
				placeholder: 'Software Engineer',
				description: 'Job title the candidate currently holds',
			},
			{
				displayName: 'Custom Fields',
				name: 'custom_fields',
				type: 'json',
				default: '{}',
				description:
					'Custom field values as a JSON object. Must be a full object. Partial updates will overwrite existing values.',
			},
			{
				displayName: 'Description',
				name: 'description',
				type: 'string',
				typeOptions: { rows: 4 },
				default: '',
				description: 'Free-text notes or summary about the candidate',
			},
			{
				displayName: 'Email',
				name: 'email',
				type: 'string',
				placeholder: 'jane.smith@company.com',
				default: '',
				description: "Candidate's primary email address",
			},
			{
				displayName: 'External ID',
				name: 'external_id',
				type: 'string',
				default: '',
				placeholder: 'EXT-00142',
				description: 'Identifier for this candidate in an external system',
			},
			{
				displayName: 'Gender',
				name: 'gender',
				type: 'options',
				default: 'unknown',
				options: GENDER_OPTIONS,
				description: "Candidate's gender",
			},
			{
				displayName: 'Latest Degree',
				name: 'latest_degree',
				type: 'string',
				default: '',
				placeholder: 'Bachelor of Science',
				description: 'Most recent academic degree obtained by the candidate',
			},
			{
				displayName: 'Latest University',
				name: 'latest_university',
				type: 'string',
				default: '',
				placeholder: 'Stanford University',
				description: 'Most recent university or institution attended by the candidate',
			},
			{
				displayName: 'Owner',
				name: 'owner',
				type: 'resourceLocator',
				default: { mode: 'list', value: '' },
				description: 'User responsible for this candidate record; defaults to the API token owner',
				modes: USER_MODES,
			},
			{
				displayName: 'Phone Number',
				name: 'phone_number',
				type: 'string',
				default: '',
				placeholder: '+1 555 000 0001',
				description: "Candidate's primary phone number",
			},
			{
				displayName: 'Source Other',
				name: 'source_other',
				type: 'string',
				default: '',
				description: 'Additional source detail â€" only used when Source Type is "Other"',
			},
			{
				displayName: 'Source Type',
				name: 'source_type',
				type: 'options',
				default: 'sourced',
				options: SOURCE_TYPE_OPTIONS,
				description: 'Channel through which the candidate was acquired',
			},
			{
				displayName: 'Zip Code',
				name: 'zipcode',
				type: 'string',
				default: '',
				placeholder: '10001',
				description: 'Postal code for the candidate address',
			},
		],
	},

	//  UPDATE
	{
		displayName: 'Candidate ID',
		name: 'candidateId',
		type: 'resourceLocator',
		required: true,
		default: { mode: 'list', value: '' },
		modes: CANDIDATE_MODES,
		displayOptions: {
			show: { resource: ['candidate'], operation: ['update'] },
		},
		description: 'Numeric ID of the candidate to update',
	},
	{
		displayName: 'Update Fields',
		name: 'updateFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: { resource: ['candidate'], operation: ['update'] },
		},
		options: [
			{
				displayName: 'Address',
				name: 'address',
				type: 'string',
				default: '',
				placeholder: '123 Main Street',
				description: 'Street address of the candidate',
			},
			{
				displayName: 'Birth Date',
				name: 'birth_date',
				type: 'dateTime',
				default: '',
				description: "Candidate's date of birth",
			},
			{
				displayName: 'Consent',
				name: 'consent',
				type: 'boolean',
				default: false,
				description:
					'Enable to record that the candidate consented to data processing under privacy regulations (GDPR / LGPD / CCPA)',
			},
			{
				displayName: 'Current Company',
				name: 'current_company',
				type: 'string',
				default: '',
				placeholder: 'Acme Corp',
				description: "Name of the candidate's current employer",
			},
			{
				displayName: 'Current Department',
				name: 'current_department',
				type: 'string',
				default: '',
				placeholder: 'Engineering',
				description: 'Department the candidate currently works in',
			},
			{
				displayName: 'Current Position',
				name: 'current_position',
				type: 'string',
				default: '',
				placeholder: 'Software Engineer',
				description: 'Job title the candidate currently holds',
			},
			{
				displayName: 'Custom Fields',
				name: 'custom_fields',
				type: 'json',
				default: '{}',
				description:
					'Custom field values as a JSON object. Must be a full object - partial updates will overwrite existing values.',
			},
			{
				displayName: 'Description',
				name: 'description',
				type: 'string',
				typeOptions: { rows: 4 },
				default: '',
				description: 'Free-text notes or summary about the candidate',
			},
			{
				displayName: 'Email',
				name: 'email',
				type: 'string',
				placeholder: 'jane.smith@company.com',
				default: '',
				description: "Candidate's primary email address",
			},
			{
				displayName: 'External ID',
				name: 'external_id',
				type: 'string',
				default: '',
				placeholder: 'EXT-00142',
				description: 'Identifier for this candidate in an external system',
			},
			{
				displayName: 'Full Name',
				name: 'full_name',
				type: 'string',
				default: '',
				placeholder: 'Jane Smith',
				description: "Candidate's full name",
			},
			{
				displayName: 'Gender',
				name: 'gender',
				type: 'options',
				default: 'unknown',
				options: GENDER_OPTIONS,
				description: "Candidate's gender",
			},
			{
				displayName: 'Latest Degree',
				name: 'latest_degree',
				type: 'string',
				default: '',
				placeholder: 'Bachelor of Science',
				description: 'Most recent academic degree obtained by the candidate',
			},
			{
				displayName: 'Latest University',
				name: 'latest_university',
				type: 'string',
				default: '',
				placeholder: 'Stanford University',
				description: 'Most recent university or institution attended by the candidate',
			},
			{
				displayName: 'Owner',
				name: 'owner',
				type: 'resourceLocator',
				default: { mode: 'list', value: '' },
				modes: USER_MODES,
				description: 'User responsible for this candidate record',
			},
			{
				displayName: 'Phone Number',
				name: 'phone_number',
				type: 'string',
				default: '',
				placeholder: '+1 555 000 0001',
				description: "Candidate's primary phone number",
			},
			{
				displayName: 'Source Other',
				name: 'source_other',
				type: 'string',
				default: '',
				description: 'Additional source detail - only used when Source Type is "Other"',
			},
			{
				displayName: 'Source Type',
				name: 'source_type',
				type: 'options',
				default: 'sourced',
				options: SOURCE_TYPE_OPTIONS,
				description: 'Channel through which the candidate was acquired',
			},
			{
				displayName: 'Zip Code',
				name: 'zipcode',
				type: 'string',
				default: '',
				placeholder: '10001',
				description: 'Postal code for the candidate address',
			},
		],
	},
];
