import type { INodeProperties } from 'n8n-workflow';
import { JOB_MODES, ORGANIZATION_MODES, USER_MODES } from './SharedFields';

export const JOB_SALARY_FREQUENCY_OPTIONS = [
	{ name: 'Hourly', value: 'hour' },
	{ name: 'Daily', value: 'day' },
	{ name: 'Weekly', value: 'week' },
	{ name: 'Monthly', value: 'month' },
	{ name: 'Annually', value: 'year' },
];
const CONTRACT_DETAILS_OPTIONS = [
	{ name: 'Apprenticeship', value: 'apprenticeship' },
	{ name: 'Consultancy', value: 'consultancy' },
	{ name: 'Contractor', value: 'contractor' },
	{ name: 'Freelance', value: 'freelance' },
	{ name: 'Full Time', value: 'full_time' },
	{ name: 'Internship', value: 'internship' },
	{ name: 'Part Time', value: 'part_time' },
	{ name: 'Temporary', value: 'temporary' },
];
const JOB_STATUS_OPTIONS = [
	{ name: 'Active', value: 'active' },
	{ name: 'Lost', value: 'lost' },
	{ name: 'On Hold', value: 'on_hold' },
	{ name: 'Won', value: 'won' },
];

export const jobOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: { resource: ['job'] },
		},
		options: [
			{
				name: 'Create',
				value: 'create',
				action: 'Create a job',
				description: 'Create a new job posting',
			},
			{
				name: 'Get',
				value: 'get',
				action: 'Get a job',
				description: 'Retrieve a job by ID',
			},
			{
				name: 'Get Many',
				value: 'getMany',
				action: 'Get many jobs',
				description: 'Retrieve a list of jobs',
			},
			{
				name: 'Update',
				value: 'update',
				action: 'Update a job',
				description: 'Update a job posting',
			},
		],
		default: 'getMany',
	},
];

export const jobFields: INodeProperties[] = [
	{
		displayName: 'Job ID',
		name: 'jobId',
		type: 'resourceLocator',
		required: true,
		default: { mode: 'list', value: '' },
		modes: JOB_MODES,
		displayOptions: {
			show: { resource: ['job'], operation: ['get'] },
		},
		description: 'Numeric ID of the job to retrieve',
	},

	//	GET MANY
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		default: false,
		displayOptions: {
			show: { resource: ['job'], operation: ['getMany'] },
		},
		description: 'Fetch every matching job instead of stopping at the limit',
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		typeOptions: { minValue: 1, maxValue: 100 },
		default: 10,
		displayOptions: {
			show: { resource: ['job'], operation: ['getMany'], returnAll: [false] },
		},
		description: 'Max number of results to return',
	},
	{
		displayName: 'Filters',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add Filter',
		default: {},
		displayOptions: {
			show: { resource: ['job'], operation: ['getMany'] },
		},
		options: [
			{
				displayName: 'Address',
				name: 'address',
				type: 'string',
				default: '',
				placeholder: '123 Main Street',
				description: 'Return jobs whose office address contains this text (partial match)',
			},
			{
				displayName: 'City',
				name: 'city',
				type: 'string',
				default: '',
				placeholder: 'New York',
				description: 'Return jobs located in this city (partial match)',
			},
			{
				displayName: 'Close At (From)',
				name: 'close_at__gte',
				type: 'dateTime',
				default: '',
				description: 'Return jobs closed on or after this date',
			},
			{
				displayName: 'Close At (To)',
				name: 'close_at__lte',
				type: 'dateTime',
				default: '',
				description: 'Return jobs closed on or before this date',
			},
			{
				displayName: 'Contract Details',
				name: 'contract_details',
				type: 'options',
				default: '',
				options: CONTRACT_DETAILS_OPTIONS,
				description: 'Return jobs with this employment contract type',
			},
			{
				displayName: 'Created At (From)',
				name: 'created_at__gte',
				type: 'dateTime',
				default: '',
				description: 'Return jobs created on or after this date',
			},
			{
				displayName: 'Created At (To)',
				name: 'created_at__lte',
				type: 'dateTime',
				default: '',
				description: 'Return jobs created on or before this date',
			},
			{
				displayName: 'Creator',
				name: 'creator_id',
				type: 'resourceLocator',
				default: { mode: 'list', value: '' },
				description: 'Return jobs created by this user',
				modes: USER_MODES,
			},
			{
				displayName: 'External ID',
				name: 'external_id',
				type: 'string',
				default: '',
				placeholder: 'EXT-00142',
				description: 'Return jobs with this exact external system ID',
			},
			{
				displayName: 'Frequency',
				name: 'frequency',
				type: 'options',
				default: '',
				description: 'Return jobs with this salary payment frequency',
				options: JOB_SALARY_FREQUENCY_OPTIONS,
			},
			{
				displayName: 'Headcount',
				name: 'headcount',
				type: 'number',
				default: '',
				description: 'Return jobs with this exact number of open positions',
			},
			{
				displayName: 'ID',
				name: 'id',
				type: 'number',
				default: '',
				description: 'Return the job with this exact ID',
			},
			{
				displayName: 'Is Published',
				name: 'is_published',
				type: 'boolean',
				default: true,
				description: 'Set to true to return only published jobs; set to false for unpublished only',
			},
			{
				displayName: 'Is Remote',
				name: 'is_remote',
				type: 'boolean',
				default: false,
				description: 'Set to true to return only remote jobs; set to false for on-site only',
			},
			{
				displayName: 'Open At (From)',
				name: 'open_at__gte',
				type: 'dateTime',
				default: '',
				description: 'Return jobs opened on or after this date',
			},
			{
				displayName: 'Open At (To)',
				name: 'open_at__lte',
				type: 'dateTime',
				default: '',
				description: 'Return jobs opened on or before this date',
			},
			{
				displayName: 'Organization',
				name: 'organization',
				type: 'resourceLocator',
				default: { mode: 'list', value: '' },
				description: 'Return jobs belonging to this organization',
				modes: ORGANIZATION_MODES,
			},
			{
				displayName: 'Owner',
				name: 'owner_id',
				type: 'resourceLocator',
				default: { mode: 'list', value: '' },
				description: 'Return jobs owned by this user',
				modes: USER_MODES,
			},
			{
				displayName: 'Position Name',
				name: 'position_name',
				type: 'string',
				default: '',
				placeholder: 'Software Engineer',
				description: 'Return jobs whose position name contains this text (partial match)',
			},
			{
				displayName: 'State',
				name: 'state',
				type: 'string',
				default: '',
				placeholder: 'New York',
				description: 'Return jobs located in this state (partial match)',
			},
			{
				displayName: 'Status',
				name: 'status',
				type: 'options',
				default: '',
				options: JOB_STATUS_OPTIONS,
				description: 'Return jobs with this pipeline status',
			},
			{
				displayName: 'Updated At (From)',
				name: 'updated_at__gte',
				type: 'dateTime',
				default: '',
				description: 'Return jobs updated on or after this date',
			},
			{
				displayName: 'Updated At (To)',
				name: 'updated_at__lte',
				type: 'dateTime',
				default: '',
				description: 'Return jobs updated on or before this date',
			},
		],
	},

	//	CREATE
	{
		displayName: 'Position Name',
		name: 'positionName',
		type: 'string',
		required: true,
		default: '',
		placeholder: 'Senior Software Engineer',
		displayOptions: {
			show: { resource: ['job'], operation: ['create'] },
		},
		description: 'Title of the job position being filled',
	},
	{
		displayName: 'Organization',
		name: 'organization',
		type: 'resourceLocator',
		default: { mode: 'list', value: '' },
		required: true,
		modes: ORGANIZATION_MODES,
		displayOptions: {
			show: { resource: ['job'], operation: ['create'] },
		},
		description: 'Organization this job belongs to',
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: { resource: ['job'], operation: ['create'] },
		},
		options: [
			{
				displayName: 'Address',
				name: 'address',
				type: 'string',
				default: '',
				placeholder: '123 Main Street',
				description: 'Street address of the office where the job will take place',
			},
			{
				displayName: 'City',
				name: 'city',
				type: 'string',
				default: '',
				placeholder: 'New York',
				description: 'City of the office where the job will take place',
			},
			{
				displayName: 'Contract Details',
				name: 'contract_details',
				type: 'options',
				default: 'full_time',
				options: CONTRACT_DETAILS_OPTIONS,
				description: 'Type of employment contract offered for this position',
			},
			{
				displayName: 'Country',
				name: 'country',
				type: 'string',
				default: '',
				placeholder: 'United States',
				description: 'Country of the office where the job will take place',
			},
			{
				displayName: 'Currency',
				name: 'currency',
				type: 'options',
				default: '',
				typeOptions: { loadOptionsMethod: 'getCurrencies' },
				description: 'Currency used for the salary range fields',
			},
			{
				displayName: 'Custom Fields',
				name: 'custom_fields',
				type: 'json',
				default: '{}',
				description:
					'Custom field values as a JSON object. Must be a full object - partial updates will overwrite existing values.',
			},
			{
				displayName: 'Description',
				name: 'description',
				type: 'string',
				typeOptions: { rows: 4 },
				default: '',
				description: 'Full description of the job, including responsibilities and requirements',
			},
			{
				displayName: 'Expected Close At',
				name: 'expected_close_at',
				type: 'dateTime',
				default: '',
				description: 'Target date by which the position should be filled',
			},
			{
				displayName: 'External ID',
				name: 'external_id',
				type: 'string',
				default: '',
				placeholder: 'EXT-00142',
				description: 'Identifier for this job in an external system',
			},
			{
				displayName: 'Frequency',
				name: 'frequency',
				type: 'options',
				default: '',
				description: 'How often the salary is paid',
				options: JOB_SALARY_FREQUENCY_OPTIONS,
			},
			{
				displayName: 'Headcount',
				name: 'headcount',
				type: 'number',
				default: 1,
				description: 'Number of open positions available for this job',
			},
			{
				displayName: 'Industry',
				name: 'industry',
				type: 'options',
				default: '',
				typeOptions: { loadOptionsMethod: 'getIndustries' },
				description: 'Industry sector this job belongs to',
			},
			{
				displayName: 'Is Pinned In Career Page',
				name: 'is_pinned_in_career_page',
				type: 'boolean',
				default: false,
				description: 'Pin this job at the top of the public career page listing',
			},
			{
				displayName: 'Is Published',
				name: 'is_published',
				type: 'boolean',
				default: false,
				description: 'Publish this job on the career page so candidates can apply',
			},
			{
				displayName: 'Is Remote',
				name: 'is_remote',
				type: 'boolean',
				default: false,
				description: 'Mark this position as fully remote',
			},
			{
				displayName: 'Is Salary Visible',
				name: 'is_salary_visible',
				type: 'boolean',
				default: false,
				description: 'Display the salary range to candidates on the career page',
			},
			{
				displayName: 'Owner',
				name: 'owner',
				type: 'resourceLocator',
				default: { mode: 'list', value: '' },
				description: 'User responsible for managing this job',
				modes: USER_MODES,
			},
			{
				displayName: 'Salary Max',
				name: 'salary_max',
				type: 'string',
				default: '',
				placeholder: '80000',
				description: 'Maximum salary offered for this position',
			},
			{
				displayName: 'Salary Min',
				name: 'salary_min',
				type: 'string',
				default: '',
				placeholder: '80000',
				description: 'Minimum salary offered for this position',
			},
			{
				displayName: 'State',
				name: 'state',
				type: 'string',
				default: '',
				placeholder: 'New York',
				description: 'State or province of the office where the job will take place',
			},
			{
				displayName: 'Status',
				name: 'status',
				type: 'options',
				default: 'active',
				options: JOB_STATUS_OPTIONS,
				description: 'Current pipeline status of the job',
			},
			{
				displayName: 'Zip Code',
				name: 'zipcode',
				type: 'string',
				default: '',
				placeholder: '10001',
				description: 'Postal code of the office where the job will take place',
			},
		],
	},

	//	UPDATE
	{
		displayName: 'Job ID',
		name: 'jobId',
		type: 'resourceLocator',
		required: true,
		default: { mode: 'list', value: '' },
		modes: JOB_MODES,
		displayOptions: {
			show: { resource: ['job'], operation: ['update'] },
		},
		description: 'Numeric ID of the job to update',
	},
	{
		displayName: 'Update Fields',
		name: 'updateFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: { resource: ['job'], operation: ['update'] },
		},
		options: [
			{
				displayName: 'Address',
				name: 'address',
				type: 'string',
				default: '',
				placeholder: '123 Main Street',
				description: 'Street address of the office where the job will take place',
			},
			{
				displayName: 'City',
				name: 'city',
				type: 'string',
				default: '',
				placeholder: 'New York',
				description: 'City of the office where the job will take place',
			},
			{
				displayName: 'Contract Details',
				name: 'contract_details',
				type: 'options',
				default: '',
				options: CONTRACT_DETAILS_OPTIONS,
				description: 'Type of employment contract offered for this position',
			},
			{
				displayName: 'Country',
				name: 'country',
				type: 'string',
				default: '',
				placeholder: 'United States',
				description: 'Country of the office where the job will take place',
			},
			{
				displayName: 'Currency',
				name: 'currency',
				type: 'options',
				default: '',
				typeOptions: { loadOptionsMethod: 'getCurrencies' },
				description: 'Currency used for the salary range fields',
			},
			{
				displayName: 'Custom Fields',
				name: 'custom_fields',
				type: 'json',
				default: '{}',
				description:
					'Custom field values as a JSON object. Must be a full object - partial updates will overwrite existing values.',
			},
			{
				displayName: 'Description',
				name: 'description',
				type: 'string',
				typeOptions: { rows: 4 },
				default: '',
				description: 'Full description of the job, including responsibilities and requirements',
			},
			{
				displayName: 'Expected Close At',
				name: 'expected_close_at',
				type: 'dateTime',
				default: '',
				description: 'Target date by which the position should be filled',
			},
			{
				displayName: 'External ID',
				name: 'external_id',
				type: 'string',
				default: '',
				placeholder: 'EXT-00142',
				description: 'Identifier for this job in an external system',
			},
			{
				displayName: 'Frequency',
				name: 'frequency',
				type: 'options',
				default: '',
				description: 'How often the salary is paid',
				options: JOB_SALARY_FREQUENCY_OPTIONS,
			},
			{
				displayName: 'Headcount',
				name: 'headcount',
				type: 'number',
				default: 1,
				description: 'Number of open positions available for this job',
			},
			{
				displayName: 'Industry',
				name: 'industry',
				type: 'options',
				default: '',
				typeOptions: { loadOptionsMethod: 'getIndustries' },
				description: 'Industry sector this job belongs to',
			},
			{
				displayName: 'Is Pinned In Career Page',
				name: 'is_pinned_in_career_page',
				type: 'boolean',
				default: false,
				description: 'Pin this job at the top of the career page',
			},
			{
				displayName: 'Is Published',
				name: 'is_published',
				type: 'boolean',
				default: false,
				description: 'Publish this job on the career page',
			},
			{
				displayName: 'Is Remote',
				name: 'is_remote',
				type: 'boolean',
				default: false,
				description: 'Mark this position as fully remote',
			},
			{
				displayName: 'Is Salary Visible',
				name: 'is_salary_visible',
				type: 'boolean',
				default: false,
				description: 'Display the salary range to candidates on the career page',
			},
			{
				displayName: 'Owner',
				name: 'owner',
				type: 'resourceLocator',
				default: { mode: 'list', value: '' },
				modes: USER_MODES,
				description: 'User responsible for managing this job',
			},
			{
				displayName: 'Position Name',
				name: 'position_name',
				type: 'string',
				default: '',
				placeholder: 'Senior Software Engineer',
				description: 'Title of the job position being filled',
			},
			{
				displayName: 'Salary Max',
				name: 'salary_max',
				type: 'string',
				default: '',
				placeholder: '80000',
				description: 'Maximum salary offered for this position',
			},
			{
				displayName: 'Salary Min',
				name: 'salary_min',
				type: 'string',
				default: '',
				placeholder: '80000',
				description: 'Minimum salary offered for this position',
			},
			{
				displayName: 'State',
				name: 'state',
				type: 'string',
				default: '',
				placeholder: 'New York',
				description: 'State or province of the office where the job will take place',
			},
			{
				displayName: 'Status',
				name: 'status',
				type: 'options',
				default: '',
				options: JOB_STATUS_OPTIONS,
				description: 'Current pipeline status of the job',
			},
			{
				displayName: 'Zip Code',
				name: 'zipcode',
				type: 'string',
				default: '',
				placeholder: '10001',
				description: 'Postal code of the office where the job will take place',
			},
		],
	},
];
