import type { INodeProperties } from 'n8n-workflow';
import { CANDIDATE_MODES, JOB_MODES, MATCH_MODES, USER_MODES } from './SharedFields';

export const matchOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: { resource: ['match'] },
		},
		options: [
			{
				name: 'Create',
				value: 'create',
				action: 'Create a match',
				description: 'Creates a new match',
			},
			{
				name: 'Get',
				value: 'get',
				action: 'Get a match',
				description: 'Retrieve a match by ID',
			},
			{
				name: 'Get Many',
				value: 'getMany',
				action: 'Get many matches',
				description: 'Retrieve a list of matches',
			},
			{
				name: 'Update',
				value: 'update',
				action: 'Update a match',
				description: 'Update a match (e.g. move pipeline stage)',
			},
		],
		default: 'getMany',
	},
];

export const matchFields: INodeProperties[] = [
	{
		displayName: 'Match ID',
		name: 'matchId',
		type: 'resourceLocator',
		required: true,
		default: { mode: 'list', value: '' },
		modes: MATCH_MODES,
		displayOptions: {
			show: { resource: ['match'], operation: ['get'] },
		},
		description: 'Numeric ID of the match to retrieve',
	},

	//	GET MANY
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		default: false,
		displayOptions: {
			show: { resource: ['match'], operation: ['getMany'] },
		},
		description: 'Fetch every match instead of stopping at the limit',
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		typeOptions: { minValue: 1, maxValue: 100 },
		default: 10,
		displayOptions: {
			show: { resource: ['match'], operation: ['getMany'], returnAll: [false] },
		},
		description: 'Max number of results to return',
	},
	{
		displayName: 'Filters',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add Filter',
		default: {},
		displayOptions: {
			show: { resource: ['match'], operation: ['getMany'] },
		},
		options: [
			{
				displayName: 'Created At (From)',
				name: 'created_at__gte',
				type: 'dateTime',
				default: '',
				description: 'Return matches created on or after this date',
			},
			{
				displayName: 'Created At (To)',
				name: 'created_at__lte',
				type: 'dateTime',
				default: '',
				description: 'Return matches created on or before this date',
			},
			{
				displayName: 'Dropped At (From)',
				name: 'dropped_at__gte',
				type: 'dateTime',
				default: '',
				description: 'Return matches where the candidate was dropped on or after this date',
			},
			{
				displayName: 'Dropped At (To)',
				name: 'dropped_at__lte',
				type: 'dateTime',
				default: '',
				description: 'Return matches where the candidate was dropped on or before this date',
			},
			{
				displayName: 'External ID',
				name: 'external_id',
				type: 'string',
				default: '',
				placeholder: 'EXT-00142',
				description: 'Return matches with this exact external system ID',
			},
			{
				displayName: 'Hired At (From)',
				name: 'hired_at__gte',
				type: 'dateTime',
				default: '',
				description: 'Return matches where the candidate was hired on or after this date',
			},
			{
				displayName: 'Hired At (To)',
				name: 'hired_at__lte',
				type: 'dateTime',
				default: '',
				description: 'Return matches where the candidate was hired on or before this date',
			},
			{
				displayName: 'Interview At (From)',
				name: 'interview_at__gte',
				type: 'dateTime',
				default: '',
				description: 'Return matches where the interview was scheduled on or after this date',
			},
			{
				displayName: 'Interview At (To)',
				name: 'interview_at__lte',
				type: 'dateTime',
				default: '',
				description: 'Return matches where the interview was scheduled on or before this date',
			},
			{
				displayName: 'Offer At (From)',
				name: 'offer_at__gte',
				type: 'dateTime',
				default: '',
				description: 'Return matches where an offer was made on or after this date',
			},
			{
				displayName: 'Offer At (To)',
				name: 'offer_at__lte',
				type: 'dateTime',
				default: '',
				description: 'Return matches where an offer was made on or before this date',
			},
			{
				displayName: 'Stage IDs',
				name: 'stage__in',
				type: 'string',
				default: '',
				placeholder: '12124,34123,56123',
				description: 'Return matches in any of these pipeline stage IDs (comma-separated)',
			},
			{
				displayName: 'Submitted At (From)',
				name: 'submitted_at__gte',
				type: 'dateTime',
				default: '',
				description: 'Return matches submitted on or after this date',
			},
			{
				displayName: 'Submitted At (To)',
				name: 'submitted_at__lte',
				type: 'dateTime',
				default: '',
				description: 'Return matches submitted on or before this date',
			},
			{
				displayName: 'Updated At (From)',
				name: 'updated_at__gte',
				type: 'dateTime',
				default: '',
				description: 'Return matches updated on or after this date',
			},
			{
				displayName: 'Updated At (To)',
				name: 'updated_at__lte',
				type: 'dateTime',
				default: '',
				description: 'Return matches updated on or before this date',
			},
		],
	},

	// CREATE
	{
		displayName: 'Candidate ID',
		name: 'candidateId',
		type: 'resourceLocator',
		required: true,
		default: { mode: 'list', value: '' },
		modes: CANDIDATE_MODES,
		displayOptions: {
			show: { resource: ['match'], operation: ['create'] },
		},
		description: 'Numeric ID of the candidate',
	},
	{
		displayName: 'Job ID',
		name: 'jobId',
		type: 'resourceLocator',
		required: true,
		default: { mode: 'list', value: '' },
		modes: JOB_MODES,
		displayOptions: {
			show: { resource: ['match'], operation: ['create'] },
		},
		description: 'Numeric ID of the job',
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: { resource: ['match'], operation: ['create'] },
		},
		options: [
			{
				displayName: 'Dropped At',
				name: 'dropped_at',
				type: 'dateTime',
				default: '',
				description: 'Date the candidate was dropped from the pipeline',
			},
			{
				displayName: 'External ID',
				name: 'external_id',
				type: 'string',
				default: '',
				placeholder: 'EXT-00142',
				description: 'Identifier for this match in an external system',
			},
			{
				displayName: 'Hired At',
				name: 'hired_at',
				type: 'dateTime',
				default: '',
				description: 'Date the candidate was hired for this position',
			},
			{
				displayName: 'Interview At',
				name: 'interview_at',
				type: 'dateTime',
				default: '',
				description: 'Date the candidate was last interviewed for this position',
			},
			{
				displayName: 'Is Active',
				name: 'is_active',
				type: 'boolean',
				default: true,
				description: 'Keep this match active in the pipeline; disable to mark it as inactive',
			},
			{
				displayName: 'Offer At',
				name: 'offer_at',
				type: 'dateTime',
				default: '',
				description: 'Date an offer was extended to the candidate',
			},
			{
				displayName: 'Owner',
				name: 'owner',
				type: 'resourceLocator',
				default: { mode: 'list', value: '' },
				description: 'User responsible for managing this pipeline entry',
				modes: USER_MODES,
			},
			{
				displayName: 'Submitted At',
				name: 'submitted_at',
				type: 'dateTime',
				default: '',
				description: 'Date the candidate was submitted to the job pipeline',
			},
		],
	},

	//	UPDATE
	{
		displayName: 'Match ID',
		name: 'matchId',
		type: 'resourceLocator',
		required: true,
		default: { mode: 'list', value: '' },
		modes: MATCH_MODES,
		displayOptions: {
			show: { resource: ['match'], operation: ['update'] },
		},
		description: 'Numeric ID of the match to update',
	},
	{
		displayName: 'Update Fields',
		name: 'updateFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: { resource: ['match'], operation: ['update'] },
		},
		options: [
			{
				displayName: 'Dropped At',
				name: 'dropped_at',
				type: 'dateTime',
				default: '',
				description: 'Date the candidate was dropped from the pipeline',
			},
			{
				displayName: 'External ID',
				name: 'external_id',
				type: 'string',
				default: '',
				placeholder: 'EXT-00142',
				description: 'Identifier for this match in an external system',
			},
			{
				displayName: 'Hired At',
				name: 'hired_at',
				type: 'dateTime',
				default: '',
				description: 'Date the candidate was hired for this position',
			},
			{
				displayName: 'Interview At',
				name: 'interview_at',
				type: 'dateTime',
				default: '',
				description: 'Date the candidate was last interviewed for this position',
			},
			{
				displayName: 'Is Active',
				name: 'is_active',
				type: 'boolean',
				default: true,
				description: 'Keep this match active in the pipeline; disable to mark it as inactive',
			},
			{
				displayName: 'Offer At',
				name: 'offer_at',
				type: 'dateTime',
				default: '',
				description: 'Date an offer was extended to the candidate',
			},
			{
				displayName: 'Owner',
				name: 'owner',
				type: 'resourceLocator',
				default: { mode: 'list', value: '' },
				modes: USER_MODES,
				description: 'User responsible for managing this pipeline entry',
			},
			{
				displayName: 'Stage',
				name: 'job_pipeline_stage',
				type: 'options',
				default: '',
				description:
					'Pipeline stage to move this match to. Loads stages from the pipeline assigned to the selected match.',
				typeOptions: {
					loadOptionsMethod: 'getMatchPipelineStages',
					loadOptionsDependsOn: ['matchId'],
				},
			},
			{
				displayName: 'Submitted At',
				name: 'submitted_at',
				type: 'dateTime',
				default: '',
				description: 'Date the candidate was submitted to the job pipeline',
			},
		],
	},
];
